[build]
command = "pip install -r requirements.txt"
functions = "netlify/functions"

[build.environment]
PYTHON_COMPILE = "false"
AWS_PYTHON_VERSION = "3.10"
PYTHON_VERSION = "3.10"
MISE_PYTHON_COMPILE = "false"

[[redirects]]
from = "/*"
to = "/.netlify/functions/flask_app"
status = 200
